profile:
  default: development
project:
  type: website
  pre-render:
    - ./pre-render.py
  post-render:
    - ./post-render.py
  render:
    - "RESUME.md"
website:
  title: "Jonas Mandel"
  site-url: https://man-jo.github.io
  page-footer:
    border: true
    background: dark
    center: 
      - text: "<b>Download PDF</b>"
        href: /index.pdf
format-links: false
format:
  html:
    page-layout: full
    theme:
      light: zephyr
      dark: solar
    css: styles.css
    link-external-newwindow: true
    canonical-url: true
  pdf:
    documentclass: article
    papersize: a4
    fontsize: 10pt
    latex-auto-install: true
    include-in-header: 
      - "pdf.KOMA.tex"
resources:
  - CNAME
filters:
  - flex-minipage-filter.lua
